# Generated by Django 3.0.2 on 2020-01-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True, verbose_name='描述')),
                ('port', models.CharField(max_length=10, verbose_name='端口')),
                ('user', models.CharField(max_length=50, verbose_name='用户名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('status', models.CharField(choices=[(0, '无法连接'), (1, '连接正常')], default=1, max_length=1, verbose_name='状态')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='上次检测时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('delete', models.CharField(choices=[(0, '已删除'), (1, '未删除')], default=1, max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '服务配置信息',
                'db_table': 'server_info',
            },
        ),
    ]
