# Generated by Django 3.0.2 on 2020-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='creater',
            field=models.CharField(default='liuchang', max_length=50, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
