# Generated by Django 3.0.2 on 2020-01-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='status',
            field=models.CharField(choices=[(0, '无法连接'), (1, '连接正常')], default='1', max_length=1, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='delete',
            field=models.CharField(choices=[(0, '已删除'), (1, '未删除')], max_length=1, verbose_name='是否删除'),
        ),
    ]
