# Generated by Django 3.0.2 on 2020-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_auto_20200115_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='user',
            field=models.CharField(default='root', max_length=50, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='delete',
            field=models.CharField(choices=[(0, '已删除'), (1, '未删除')], default=1, max_length=1, verbose_name='是否删除'),
        ),
    ]
