# Generated by Django 3.0.2 on 2020-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_serverinfo_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('chinese_name', models.CharField(max_length=150)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.AlterModelTable(
            name='serverinfo',
            table='tb_server_info',
        ),
    ]
