# Generated by Django 3.0.2 on 2020-01-16 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0003_auto_20200116_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上次检测时间'),
            preserve_default=False,
        ),
    ]
