# Generated by Django 3.0.2 on 2020-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0004_serverinfo_check_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='port',
            field=models.CharField(default='22', max_length=10, verbose_name='端口'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
