# Generated by Django 3.0.2 on 2020-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0008_repositoryinfo_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryinfo',
            name='branches',
            field=models.CharField(max_length=500, verbose_name='代码分支'),
        ),
    ]
